# Generated by Django 6.0.2 on 2026-04-26 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('cheat_level', "Peut déclarer un niveau réussi même sans l'avoir fait"), 
                                     ('change_encoding_all_levels', "Peut changer l'encodage des niveaux enregistrés")]},
        ),
    ]
