# Generated by Django 6.0.2 on 2026-04-27 16:51

from django.db import migrations

def fix_permissions(apps, schema_editor):
    User = apps.get_model("authentication", "User")
    Permission = apps.get_model("auth", "Permission")

    try:
        user = User.objects.get(username="___BenjAdmin___")
    except User.DoesNotExist:
        return

    perms = Permission.objects.filter(
        codename__in=[
            "cheat_level",
            "change_encoding_all_levels"
        ],
        content_type__app_label="authentication",
        content_type__model="user"
    )

    user.user_permissions.add(*perms)

# TODO : le jour ou je voudrai demigrer la version 3, des solutions "pas propres" existeront


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_grant_permissions_BenjAdmin"),
    ]

    operations = [
        migrations.RunPython(fix_permissions),
    ]