# Generated by Django 6.0.2 on 2026-04-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_management', '0002_level_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
