# Generated by Django 6.0.2 on 2026-04-14 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_management', '0005_level_fill_positions_author_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AlterField(
            model_name='level',
            name='position',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(fields=('creator', 'position'), name='unique_position_per_creator'),
        ),
    ]
