# Generated by Django 6.0.2 on 2026-04-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_management', '0006_alter_level_options_alter_level_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
