# Generated by Django 6.0.2 on 2026-04-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level_management', '0007_alter_level_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='data',
            new_name='lvData',
        ),
    ]
