# Generated by Django 6.0.2 on 2026-05-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_management', '0009_levelcompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelcompletion',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('super', 'Super')], default='normal', max_length=10),
        ),
    ]
